alias ll="ls -lha"
alias python="python2"
alias rabbitmqctl="/usr/local/sbin/rabbitmqctl"
export PYTHONPATH="/Users/hugues/Scortex/sensei"
export GIT_AUTHOR_NAME="Hugues Poiget"
export GIT_AUTHOR_EMAIL="hpoiget@scortex.io"
export GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
export GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
